### ISSUE TITLE
Discarding Sensor Data with Quality_Low (1 Star)

### ISSUE THREAD

**Issue by dejab** [spbrogan/mopeka_pro_check#6]
Not sure this is the best place to put this.

The sensor code discards data from the Mopeka Sensor that is marked as QUALITY_LOW (1 Star)
I realize the data reliabilty issue associated with the star rating, however, some LPG tanks just wont give higher quality readings due to debris inside tank, corrosion, paint job on outside of tank, etc...  Also, the Mopeka App accepts and displays 1-star data quality.

Please consider an option to select, per tank, the lowest quality of data allowed.

I myself have two 500 gallon tanks.  One I can get a 3 star rating, the other 1 star only (sometimes it shows 2 star)

Thanks for the time spent on this project.

**Comment by spbrogan** [comment]
I am archiving this project as it uses an older/unsupported ble stack.  There is now a native integration for home assistant.  
it still has the same problem you mentioned.  I would suggest opening a bug on that component. 

Details can be found here:
https://github.com/spbrogan/sensor.mopeka_pro_check/discussions/22

There is a great esphome integration that works well and is easy to use.
Please checkout the esphome integration here https://esphome.io/components/sensor/mopeka_pro_check.html?highlight=mopeka

Thanks
